### ISSUE TITLE
ctrl-alt-r in not invoking js-refactoring function in Atom

### ISSUE THREAD

**Issue by Zephilim** [hax/refactor#45]
This plugin is not working. I have it installed in Atom and it appears to be activated. However, if I go to the Packages menu, there is no entry for either refactor or js-refactor. If I select a symbol, then hit ctrl-alt-r, then nothing happens.

**Comment by ChrislyBear-GH** [comment]
Same here. It's broken.

**Comment by piersg** [comment]
+1. Seems installed, shortcut not doing anything. Atom Mac 1.12.9

**Comment by zecarrera** [comment]
I have also installed, and trying to use it on Atom Mac 1.18.0... but can't seem to get it to work

**Comment by gamaralf** [comment]
+1. The "coffee-reactor" plugin is not working either, the problem seems to be "refactor". 

I am using Atom "1.19.3 x64"  on Ubuntu Linux.

**Comment by vmasrani** [comment]
+1. Same here, Atom Mac 1.19.2 x64

**Comment by hax** [comment]
Both js-refactor and coffee-refactor plugins still work properly on recent Atom 1.19.x though there may be bugs.

If you meet problem, please give details such as the error info or the code snippet. 

Note, you must see the background like selection (or colored underlines in the case of js-refactor) on var names, or there will be no effect for `ctrl-alt-r` because it's not recognized as a var name and that means nothing could be refactor. If you think the symbol on the cursor position should be valid names which can be refactor, pls submit issues to js-refactor or coffee-refactor repos and paste the problematic codes.

Thank you.
